### PR TITLE
Image cutout

### PR DESCRIPTION
**Pull request by weaverba137**
This PR adds an image cutout (provided by the DECaLS viewer) along with a link to the main viewer site (opens in a new window/tab).  Also cleans up the HTML in the metadata displays.

### CODE REVIEW

**Comment by weaverba137** [comment]
PS, I have several other things that I've implemented, but I'm trying to break them up into "atomic" PRs.

**Comment by weaverba137** [comment]
That was close!  The merge happened seconds after my last commit!

**Comment by sbailey** [comment]
@weaverba137 I trusted you to have everything in before opening the PR... :)

We'll need to play with the layout a bit; jupyter doesn't seem to auto-resize with my window enough to be able to see both the image cutout and the zoom window at the same time.  But thanks for adding this.  Nice.

**Comment by weaverba137** [comment]
Yes, that is a problem I'm aware of.  On some notebook servers I have added a package called `jupyter_full_width`, available from conda-forge, that adds a button to make the notebook use the full width of the browser.

**Pull request merged**
