### PR TITLE
Spectral lines

### PR DESCRIPTION
**Pull request by weaverba137**
This PR adds basic support for the display of known spectral lines, using a library derived from SDSS. The updated notebook shows the available controls.

Important note:  I tested this at NERSC with desiconda/20180518-1.2.5-spec, which has bokeh/0.12.16.  In earlier versions, the spectral line *updates* do not work.  That is, you can *display* the lines, but changes from one spectrum to the next do not get applied, and the display toggles do not work.  For example, the default desiconda/20180130-1.2.4-spec has bokeh/0.12.13.

### CODE REVIEW

**Comment by weaverba137** [comment]
Note, I've made some changes to the notebook.  I think a procedure worth trying is:

1. Make all the changes you want to the notebook.
2. Select "Restart & Clear Output" in the Kernel menu.
3. Save the notebook.
4. Check in and push.

This *should* highlight the changes to the input cells, without the distractions of changes to the output.

**Comment by sbailey** [comment]
Thanks for adding this feature, though I find that there are so many lines with overlapping labels that they aren't useful yet.

image

Suggestions:
* Default to not showing the lines upon `sp.plot()`.  That way if the user doesn't do anything, they still get the same thing as before.
* Use smaller less brightly colored labels with more vertical steps to avoid overlaps
* Since the spectra themselves are drawn in blue, red, and maroon, use something other than those colors for the emission and absorption lines to distinguish the labels/highlights from the data.
* Position the labels closer to the top/bottom of the plot so that they have less overlap with the spectrum in the middle that you are trying to look at.
* Drop the wavelength numbers from the labels (or make them optional) to reduce the amount of label overlap
* Use fewer lines, perhaps with a default basic set with an option to show all.  Nominally I'd suggest H-alpha, H-beta, [OII], [OIII], Ca H & K.  (see http://magnum.anu.edu.au/%7ETDFgg/ for the lines that 2dF chose to keep).
  * bonus points for using a different set for galaxies vs. QSOs vs. stars, e.g. for QSO LyA, Si IV, C IV, C III], Mg II, H alpha, beta, gamma, delta, and [O III]
  * extra bonus points for showing more lines with more zoom in, but that smells like scope creep for this initial PR
* Allow `sp.emission()` without an argument to toggle the display state whatever it is, while still retaining `sp.emission(True)` and `sp.emission(False)` to force it on/off.

For comparison, this is a really nice example of labeling lines in a non-cluttered way: http://www.sdss.org/wp-content/uploads/2014/11/sdss_grid_spec.png .  I recognize that those have the advantage of being high S/N spectra (and hand tuned labels?), but that level of clarity is still something that we should aspire to.

**Comment by weaverba137** [comment]
@sbailey, could you please provide a more specific link to the 2dF spectral lines?

**Comment by sbailey** [comment]
Hmm, it appears that my 2dF link was truncated when I put it into github, and I haven't re-discovered the original.  It may have been something similar to:


or

**Comment by weaverba137** [comment]
Not ready to merge yet, but substantial progress:

* Line display is off by default.
* `sp.emission()`, `sp.absorption()` called without arguments will toggle the existing state.
* The line labels are shorter.  Toggling longer names will be reserved for another issue/PR.
* Based on the examples you gave me, the list of lines is not substantially different from those examples.  You may want to look closer, but I don't see any reason to change them at this point.  Augmenting the list could be moved to another issue/PR.
* I don't think there is much need to change the set of lines based on spectral type, because the lines are already displayed based on the redshift of the object.  For example, a QSO with z=2 will have QSO lines visible because those are redshifted into the visible wavelength range.  Similarly a low-redshift galaxy won't have Lyman-alpha displayed.
* I am still working on the line/label positions.  I think I have a solution that will work, and will be similar to the SDSS example you provided, but I still need to work out the correct scaling.

**Comment by weaverba137** [comment]
@sbailey, please give this a try.  I'm reasonably satisfied with the location and appearance of the lines.  I suggest we get the functionality in, and then tweak the appearance as needed later.

**Comment by sbailey** [comment]
OK, thanks.  Merging now and we can continue to tweak appearance in future updates.

**Pull request merged**
